version: '3.5'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    command: ${DOCKER_COMPOSE_COMMAND}
    build:
      context: .
      target: ${DOCKER_COMPOSE_TARGET}
    image: ${DOCKER_IMAGE_NAME}
    ports:
      - '3000:3000'
      - '9229:9229'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - POSTGRES_DATABASE_URL=${POSTGRES_DATABASE_URL}
